//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.HR.WebApp.HRServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeContract", Namespace="http://schemas.datacontract.org/2004/07/WCF.HR.Service.Lib.Contracts")]
    [System.SerializableAttribute()]
    public partial class EmployeeContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HireDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CommissionPctField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ManagerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> DepartmentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime HireDate {
            get {
                return this.HireDateField;
            }
            set {
                if ((this.HireDateField.Equals(value) != true)) {
                    this.HireDateField = value;
                    this.RaisePropertyChanged("HireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string JobId {
            get {
                return this.JobIdField;
            }
            set {
                if ((object.ReferenceEquals(this.JobIdField, value) != true)) {
                    this.JobIdField = value;
                    this.RaisePropertyChanged("JobId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<decimal> Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<decimal> CommissionPct {
            get {
                return this.CommissionPctField;
            }
            set {
                if ((this.CommissionPctField.Equals(value) != true)) {
                    this.CommissionPctField = value;
                    this.RaisePropertyChanged("CommissionPct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<int> ManagerId {
            get {
                return this.ManagerIdField;
            }
            set {
                if ((this.ManagerIdField.Equals(value) != true)) {
                    this.ManagerIdField = value;
                    this.RaisePropertyChanged("ManagerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<short> DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((this.DepartmentIdField.Equals(value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HRServiceReference.IHR")]
    public interface IHR {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployees", ReplyAction="http://tempuri.org/IHR/GetEmployeesResponse")]
        System.Collections.Generic.List<WCF.HR.WebApp.HRServiceReference.EmployeeContract> GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/GetEmployees", ReplyAction="http://tempuri.org/IHR/GetEmployeesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WCF.HR.WebApp.HRServiceReference.EmployeeContract>> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/SaveEmployee", ReplyAction="http://tempuri.org/IHR/SaveEmployeeResponse")]
        WCF.HR.WebApp.HRServiceReference.EmployeeContract SaveEmployee(WCF.HR.WebApp.HRServiceReference.EmployeeContract employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/SaveEmployee", ReplyAction="http://tempuri.org/IHR/SaveEmployeeResponse")]
        System.Threading.Tasks.Task<WCF.HR.WebApp.HRServiceReference.EmployeeContract> SaveEmployeeAsync(WCF.HR.WebApp.HRServiceReference.EmployeeContract employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/SaveSalaryHistory", ReplyAction="http://tempuri.org/IHR/SaveSalaryHistoryResponse")]
        void SaveSalaryHistory(WCF.HR.WebApp.HRServiceReference.EmployeeContract employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/SaveSalaryHistory", ReplyAction="http://tempuri.org/IHR/SaveSalaryHistoryResponse")]
        System.Threading.Tasks.Task SaveSalaryHistoryAsync(WCF.HR.WebApp.HRServiceReference.EmployeeContract employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/Hola", ReplyAction="http://tempuri.org/IHR/HolaResponse")]
        string Hola();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR/Hola", ReplyAction="http://tempuri.org/IHR/HolaResponse")]
        System.Threading.Tasks.Task<string> HolaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHRChannel : WCF.HR.WebApp.HRServiceReference.IHR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HRClient : System.ServiceModel.ClientBase<WCF.HR.WebApp.HRServiceReference.IHR>, WCF.HR.WebApp.HRServiceReference.IHR {
        
        public HRClient() {
        }
        
        public HRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WCF.HR.WebApp.HRServiceReference.EmployeeContract> GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WCF.HR.WebApp.HRServiceReference.EmployeeContract>> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public WCF.HR.WebApp.HRServiceReference.EmployeeContract SaveEmployee(WCF.HR.WebApp.HRServiceReference.EmployeeContract employee) {
            return base.Channel.SaveEmployee(employee);
        }
        
        public System.Threading.Tasks.Task<WCF.HR.WebApp.HRServiceReference.EmployeeContract> SaveEmployeeAsync(WCF.HR.WebApp.HRServiceReference.EmployeeContract employee) {
            return base.Channel.SaveEmployeeAsync(employee);
        }
        
        public void SaveSalaryHistory(WCF.HR.WebApp.HRServiceReference.EmployeeContract employee) {
            base.Channel.SaveSalaryHistory(employee);
        }
        
        public System.Threading.Tasks.Task SaveSalaryHistoryAsync(WCF.HR.WebApp.HRServiceReference.EmployeeContract employee) {
            return base.Channel.SaveSalaryHistoryAsync(employee);
        }
        
        public string Hola() {
            return base.Channel.Hola();
        }
        
        public System.Threading.Tasks.Task<string> HolaAsync() {
            return base.Channel.HolaAsync();
        }
    }
}
