//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courses.Client.CoursesServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/Courses.Service.Model.Contracts")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMsg", Namespace="http://schemas.datacontract.org/2004/07/Courses.Service.Model.Util")]
    [System.SerializableAttribute()]
    public partial class ReturnMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMsg {
            get {
                return this.ExceptionMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMsgField, value) != true)) {
                    this.ExceptionMsgField = value;
                    this.RaisePropertyChanged("ExceptionMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoursesServiceReference.ICourses")]
    public interface ICourses {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourses/AddToCourses", ReplyAction="http://tempuri.org/ICourses/AddToCoursesResponse")]
        void AddToCourses(Courses.Client.CoursesServiceReference.Course course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourses/AddToCourses", ReplyAction="http://tempuri.org/ICourses/AddToCoursesResponse")]
        System.Threading.Tasks.Task AddToCoursesAsync(Courses.Client.CoursesServiceReference.Course course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourses/ListCourses", ReplyAction="http://tempuri.org/ICourses/ListCoursesResponse")]
        Courses.Client.CoursesServiceReference.ListCoursesResponse ListCourses(Courses.Client.CoursesServiceReference.ListCoursesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourses/ListCourses", ReplyAction="http://tempuri.org/ICourses/ListCoursesResponse")]
        System.Threading.Tasks.Task<Courses.Client.CoursesServiceReference.ListCoursesResponse> ListCoursesAsync(Courses.Client.CoursesServiceReference.ListCoursesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListCourses", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListCoursesRequest {
        
        public ListCoursesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListCoursesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Courses.Client.CoursesServiceReference.ReturnMsg ListCoursesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<Courses.Client.CoursesServiceReference.Course> Courses;
        
        public ListCoursesResponse() {
        }
        
        public ListCoursesResponse(Courses.Client.CoursesServiceReference.ReturnMsg ListCoursesResult, System.Collections.Generic.List<Courses.Client.CoursesServiceReference.Course> Courses) {
            this.ListCoursesResult = ListCoursesResult;
            this.Courses = Courses;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoursesChannel : Courses.Client.CoursesServiceReference.ICourses, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoursesClient : System.ServiceModel.ClientBase<Courses.Client.CoursesServiceReference.ICourses>, Courses.Client.CoursesServiceReference.ICourses {
        
        public CoursesClient() {
        }
        
        public CoursesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoursesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoursesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoursesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddToCourses(Courses.Client.CoursesServiceReference.Course course) {
            base.Channel.AddToCourses(course);
        }
        
        public System.Threading.Tasks.Task AddToCoursesAsync(Courses.Client.CoursesServiceReference.Course course) {
            return base.Channel.AddToCoursesAsync(course);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Courses.Client.CoursesServiceReference.ListCoursesResponse Courses.Client.CoursesServiceReference.ICourses.ListCourses(Courses.Client.CoursesServiceReference.ListCoursesRequest request) {
            return base.Channel.ListCourses(request);
        }
        
        public Courses.Client.CoursesServiceReference.ReturnMsg ListCourses(out System.Collections.Generic.List<Courses.Client.CoursesServiceReference.Course> Courses) {
            Courses.Client.CoursesServiceReference.ListCoursesRequest inValue = new Courses.Client.CoursesServiceReference.ListCoursesRequest();
            Courses.Client.CoursesServiceReference.ListCoursesResponse retVal = ((Courses.Client.CoursesServiceReference.ICourses)(this)).ListCourses(inValue);
            Courses = retVal.Courses;
            return retVal.ListCoursesResult;
        }
        
        public System.Threading.Tasks.Task<Courses.Client.CoursesServiceReference.ListCoursesResponse> ListCoursesAsync(Courses.Client.CoursesServiceReference.ListCoursesRequest request) {
            return base.Channel.ListCoursesAsync(request);
        }
    }
}
