//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wcf.Hr.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALARY_HISTORY
    {
        public int EMPLOYEE_ID { get; set; }
        public short SEQ { get; set; }
        public System.DateTime START_DATE { get; set; }
        public decimal SALARY { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
